export const projects = [
  {
    id: "PJ-001",
    projectname: "Taskora Mobile Version",
    clientname: "Johan Doe",
    status: "Active",
    deadline: "2026-05-04",
    progressStatus: "In Progress",
    priority: "High",
  },
  {
    id: "PJ-002",
    projectname: "Payroll System UI",
    clientname: "Sam Milby",
    status: "Active",
    deadline: "2026-06-10",
    progressStatus: "Planning",
    priority: "Medium",
  },
  {
    id: "PJ-003",
    projectname: "Smart Helmet Dashboard",
    clientname: "John Stone",
    status: "Active",
    deadline: "2026-07-15",
    progressStatus: "In Progress",
    priority: "High",
  },
  {
    id: "PJ-004",
    projectname: "CSIT Fest Website",
    clientname: "Sassy Ser",
    status: "Completed",
    deadline: "2026-03-20",
    progressStatus: "Completed",
    priority: "Low",
  },
  {
    id: "PJ-005",
    projectname: "Travel Landing Page",
    clientname: "John Dao",
    status: "Active",
    deadline: "2026-08-01",
    progressStatus: "In Progress",
    priority: "Medium",
  },
  {
    id: "PJ-006",
    projectname: "E-commerce Redesign",
    clientname: "Sam Sulek",
    status: "Completed",
    deadline: "2026-02-18",
    progressStatus: "Completed",
    priority: "High",
  },
  {
    id: "PJ-007",
    projectname: "Portfolio Revamp",
    clientname: "Kouichi Guisihan",
    status: "Active",
    deadline: "2026-09-05",
    progressStatus: "Planning",
    priority: "Low",
  },
];